[Feat] - 어드민 워크스페이스 추가
KioSchool/KioSchool pull request #100
Opened 2024-08-20 16:19 UTC by whddltjdwhd

## 📚 개요

![image](https://github.com/user-attachments/assets/d5dda0f9-892f-4621-9f66-130edc8140f5)

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

- 슈퍼어드민 워크스페이스를 추가했습니다.
- 워크스페이스 이름을 기반으로 검색이 가능합니다.
- react-paginate 라이브러리를 통해 페이지네이션 기능을 구현했습니다.

2024-08-20 17:10 UTC, Ji-InPark requested changes
책임의 소재만 명확하면 될 것 같습니다.
리뷰 보시고 반영해주세요.

2024-08-20 17:10 UTC, Ji-InPark commented on src/hooks/useApi.tsx
> +    }
에러 형식이 다양해서 헷갈리는데 권한 없음도 403으로 통일시켜두겠습니다.
403으로 변경해주세요

2024-08-20 17:10 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
> +    <AppContainer justifyValue={'space-between'} flexDirection={'row'}>
row로 되는게 맞나요?

2024-08-20 17:10 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrder.tsx
> +  align-items: center;
필요한 부분인가요?

2024-08-20 17:10 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderManage.tsx
> +    <AppContainer justifyValue={'center'} useNavBackground={true} flexDirection={'row'}>
row가 맞나요?

2024-08-20 17:10 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +        <ContentContainer justifyCenter={workspaces.numberOfElements > 0}>
justifyCenter={workspaces.numberOfElements > 0}
이 코드가 뜻하는 바가 뭔가요?

2024-08-20 17:10 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +              {index < workspaces.content.length - 1 && <HorizontalLine />}
이건 의미하는 바가 뭔가요?

2024-08-20 17:10 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +          {workspaces.numberOfElements === 0 && <EmptyLabel>찾고자 하는 워크스페이스가 없습니다.</EmptyLabel>}
이런식으로 워크스페이스가 없을 때 표시하고 싶은게 다르다 하면 위에 콘텐츠 부분 자체를 컴포넌트로 묶고 그 내부에서 분기처리하게끔 보여주는게 좀더 깔끔합니다.

그러면 early return 가능해지구요

2024-08-23 14:37 UTC, whddltjdwhd commented on src/components/SuperAdmin/workspace/SuperAdminSearchBar.tsx
> +    }
fetchAllWorkspaces 안에 그냥 name을 넘겨봤습니다.

```
  const fetchAllWorkspaces = (page: number, size: number, name?: string) => {
    superAdminApi
      .get<WorkspaceList>('/workspaces', { params: { page, size, name } })
      .then((res) => {
        setUserWorkspaceList(res.data);
      })
      .catch((error) => console.error(error));
  };
```

![image](https://github.com/user-attachments/assets/b61319c9-a10d-4216-a32c-00a9a71ab8e1)


그랬더니 params에 name 필드가 생겼습니다. 이래도 괜찮은건지 궁금합니다!

참고로 이전 코드의 경우엔 다음과 같습니다 : )

![image](https://github.com/user-attachments/assets/52d42e85-e08e-4ee5-971d-e864ab07822c)

2024-08-23 14:42 UTC, whddltjdwhd commented on src/components/SuperAdmin/workspace/SuperAdminWorkspaceContent.tsx
> +`;
음 그럼 이 부분은 일단 navBarLabelStyle의 내용을 복붙해서 사용하구, 다음 PR때 프로젝트 전체에 대해 공용 스타일을 적용하겠습니다 😊

```
${navBarLabelStyle} 

->

text-align: center;
  font-size: 18px;
  font-weight: 400;
  text-decoration: none;
  color: #5c5c5c;
  cursor: pointer;
  transition: ease-in 0.1s;
  &:hover {
    color: #eb6d09;
    text-decoration: underline;
  }
```

2024-08-23 14:50 UTC, whddltjdwhd commented on src/pages/Admin/AdminHome.tsx
> +    <AppContainer justifyValue={'space-between'} flexDirection={'row'}>
저 부분이 AppContainer의 MainContainer 내부 SubContainer의 flex-direction 속성을 의미하는건데, 지금은 그냥 flexDirection 이름으로 되어있어서 혼란을 야기할 수 있을 것 같습니다. prop 이름을 subFlexDirection과 같이 좀 더 정확히 적을까요?

![image](https://github.com/user-attachments/assets/ff787f6c-b8fb-4058-a269-d137cbc7a6da)

2024-08-23 15:06 UTC, whddltjdwhd commented on src/pages/Admin/order/AdminOrderManage.tsx
> +    <AppContainer justifyValue={'center'} useNavBackground={true} flexDirection={'row'}>
수정했습니다~

2024-08-23 15:12 UTC, Ji-InPark commented on src/components/SuperAdmin/workspace/SuperAdminSearchBar.tsx
> +    }
[src/components/SuperAdmin/workspace/SuperAdminSearchBar.tsx](https://github.com/KioSchool/KioSchool/pull/100/files/72a2a86e974dae4b3036ee89a84ee0df7504dc0b#diff-3bf0a874eeb5204ce99050fbe1f2d48502fa3b03bed90831413f5490de1411aa)
Comment on lines +43 to +49
    if (e.key === 'Enter' && ref && typeof ref !== 'function') {
      if (ref.current?.value) {
        fetchAllWorkspaces(1, 6, ref.current.value);
      } else {
        fetchAllWorkspaces(1, 6);
      }
    }
[Member](https://github.com/KioSchool/KioSchool/commits?author=Ji-InPark)
@[Ji-InPark](https://github.com/Ji-InPark) Ji-InPark [3 days ago](https://github.com/KioSchool/KioSchool/pull/100#discussion_r1723643356)
if문 invert 시켜주세요

그리고 fetchAllWorkspaces 안에서 분기처리해서 오버로딩 가능하게끔 구현하는게 더 좋을 것 같기도 합니다.

[Member](https://github.com/KioSchool/KioSchool/commits?author=whddltjdwhd)
Author
@[whddltjdwhd](https://github.com/whddltjdwhd) whddltjdwhd [33 minutes ago](https://github.com/KioSchool/KioSchool/pull/100#discussion_r1729084023)
fetchAllWorkspaces 안에 그냥 name을 넘겨봤습니다.

  const fetchAllWorkspaces = (page: number, size: number, name?: string) => {
    superAdminApi
      .get<WorkspaceList>('/workspaces', { params: { page, size, name } })
      .then((res) => {
        setUserWorkspaceList(res.data);
      })
      .catch((error) => console.error(error));
  };

2024-08-23 15:40 UTC, whddltjdwhd commented on src/pages/Admin/order/AdminOrder.tsx
> +  align-items: center;
넵 필요합니다!

2024-08-23 15:48 UTC, whddltjdwhd commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +        <ContentContainer justifyCenter={workspaces.numberOfElements > 0}>
![image](https://github.com/user-attachments/assets/1e153005-982b-454b-8df2-9677cf69b7ae)

워크스페이스들을 보여주는 컨테이너가 justify-content: flex-start로 되어있습니다. 그 이유는 이렇게 1개의 워크스페이스만 보여지는 경우, 중앙에 정렬되어 있는 것 보단 상단에 정렬되어 있는 것이 더 보기 좋다고 판단했기 때문입니다.

![image](https://github.com/user-attachments/assets/b3090bdb-87ee-498c-8fee-cbefc0d00752)

따라서

```
workspaces.numberOfElements > 0
```

해당 코드는! 보여줄 워크스페이스가 없을 경우에 <EmptyLabel>을 보여주게 되는데, 이때는 중앙으로 정렬되어 있으면 좋을 것 같아서 justifyCenter라는 prop을 만든 것 입니다.

![image](https://github.com/user-attachments/assets/dbb41308-0123-4065-9916-f63a38746f3d)

2024-08-23 15:50 UTC, whddltjdwhd commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +              {index < workspaces.content.length - 1 && <HorizontalLine />}
![image](https://github.com/user-attachments/assets/04ccd6c7-a004-470b-9f94-0543228e182b)

디자인 적용시에 각 워크스페이스들 사이에 존재하는 줄을 구현하고자 했습니다.

2024-08-23 19:24 UTC, Ji-InPark commented on src/components/SuperAdmin/workspace/SuperAdminSearchBar.tsx
> +    }
```ts
  const fetchAllWorkspaces = (page: number, size: number, name?: string) => {
	const params = { page, size }
	if(name !== null) params.add({name: name})

    superAdminApi
      .get<WorkspaceList>('/workspaces', { params })
      .then((res) => {
        setUserWorkspaceList(res.data);
      })
      .catch((error) => console.error(error));
  };
```

그냥 막쓴거라서 문법적으로 맞을지는 모르겟는데요 이런 느낌을 원했습니다

2024-08-23 19:26 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
> +    <AppContainer justifyValue={'space-between'} flexDirection={'row'}>
흠.. subFlexDirection 이것도 그다지 좋은 이름은 아닌거 같아요
저 내용이 보통 content가 들어간다면 contentDirection이나 뭐 그런걸로 적으면 좋을것 같은데... 암튼 하는일에 맞는 이름이면 좋을 것 같아요

2024-08-23 19:27 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrder.tsx
> +  align-items: center;
이유를 물어본거였어요 😄

2024-08-23 19:31 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +        <ContentContainer justifyCenter={workspaces.numberOfElements > 0}>
이해했습니다.
그러면 해당 조건문을 변수로 받아서 써주면 더 좋을 것 같네요

2024-08-23 19:32 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +              {index < workspaces.content.length - 1 && <HorizontalLine />}
여기도 조건문을 따로 뺄 수 있으면 가장 좋긴할거 같은데.. map 내부라서 애매하네요
일단 알겠습니다

2024-08-23 19:41 UTC, Ji-InPark reviewed
답변 안하신 리뷰들 한 번 확인해주세요~

2024-08-23 19:41 UTC, Ji-InPark commented on src/components/SuperAdmin/workspace/SuperAdminWorkspaceContent.tsx
> +      <SubLabelContainer>{subLabelContents}</SubLabelContainer>
사실 변수명이 이러면 이게 어떤 역할을 하는지 알 수가 없습니다
제가 의도한건 workspaceInfo 와 같이 해당 문구가 어떤 역할을 하는지에 대해서 적어달라는 거였습니다.

2024-08-23 19:41 UTC, Ji-InPark commented on src/types/index.ts
https://github.com/Ji-InPark/k-agent.service/blob/master/src/types/index.ts#L19-L46

이거 참고해서 generic으로 구현해주세요

2024-08-24 06:45 UTC, Ji-InPark commented on src/components/common/pagination/Pagination.tsx
> +  name?: string;
더 좋은 방법이 있을거 같긴한데 이건 나중에 해도 괜찮을것 같네요

2024-08-24 07:01 UTC, Ji-InPark reviewed
조금만 더 힘내봅시다!

2024-08-24 07:01 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +  const contentsJustifyCenter = workspaces.numberOfElements > 0;
이것도 사실 이름이 정말 어떤 의미인지 지어주는게 좋습니다.

현재 사용되는 부분을 보면 <ContentContainer justifyCenter={contentsJustifyCenter}> 이렇게 사용되는데 이 부분만 보게 되면 언제 center가 되는지는 결국 다시 변수까지 와서 해석해야합니다.

딱 저렇게 사용되는 부분만 봐도 코드가 이해되게끔(코드가 다 잘 돌아간다는 가정하에) 이름을 지어주는게 좋습니다.

2024-08-24 07:11 UTC, whddltjdwhd commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +  const contentsJustifyCenter = workspaces.numberOfElements > 0;
justifyCenterWhenNoElements 이런식이어도 괜찮을까요??

2024-08-24 07:15 UTC, whddltjdwhd commented on src/components/common/pagination/Pagination.tsx
> +  }, []);
아하 그럼 기존 리뷰대로 초기화 하는 부분을 pagintaion 컴포넌트에서 제거하겠습니다!

2024-08-24 07:35 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +  const contentsJustifyCenter = workspaces.numberOfElements > 0;
justifyCenter는 이미 파라매터 이름으로 보여주고 있는 상황이다 보니 그 부분은 중복이라고 보입니다.
빼고 NoElements 정도 또는 EmptyWorkspaces 정도면 좋을 것 같네요

2024-08-24 07:50 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +        />
size를 이렇게 받게되면 문제가 발생하는데 어떤 문제일까요??

2024-08-24 07:50 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +        />
참고로 클린 코드와 같은 가독성 문제가 아니라 진짜 기능 문제입니다

2024-08-24 07:50 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +    fetchAllWorkspaces(1, 6);
이런 상수는 웬만하면 선언해서 사용해주세요.

2024-08-24 07:50 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +  const EmptyWorkspaces = workspaces.numberOfElements === 0;
camel case...

2024-08-24 07:50 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrder.tsx
> +  align-items: center;
어떤 이유에서 필요한가요

2024-08-24 07:55 UTC, whddltjdwhd commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +        />
음 . . . 제가 이해하기로는 저 size가 한 페이지에 몇 개의 요소를 보여줄 지를 정하는 변수로 알고 있습니다. 저렇게 하면 어떤 문제가 발생하나요??

2024-08-24 07:56 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +        />
만약 검색해서 받아온 워크스페이스 개수가 6개 미만이고
다음에 검색한 워크스페이스 개수가 6개 이상이라면??

2024-08-24 08:08 UTC, whddltjdwhd commented
![image](https://github.com/user-attachments/assets/6b43d5d7-6697-4553-b25f-4b402feeadff)
있을때
![image](https://github.com/user-attachments/assets/bbb3d510-d570-4e75-9e76-b244a8f19461)
없을때

현재 키오스쿨 페이지에는 있을때와 같이 되어 있어서 해당 구문을 넣었습니다!

2024-08-25 09:07 UTC, Ji-InPark approved these changes
이것만 확인해주세요~

2024-08-25 09:07 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +    fetchAllWorkspaces(1, size);
아마 page 0 index일겁니다

2024-08-25 09:18 UTC, Ji-InPark approved these changes
Rebase하고 머지해주세요 수고하셨습니다~
![image](https://github.com/user-attachments/assets/ba98818e-ce7a-4543-8e39-1203677f1bc7)

2024-08-25 09:22 UTC, merged