FEAT - 테이블 별 주문 내역 확인 페이지 구현
KioSchool/KioSchool pull request #124
Opened 2024-10-08 12:24 UTC by whddltjdwhd

## 📚 개요

https://github.com/user-attachments/assets/2986eba3-2bc6-4ea1-bfe3-ae7d60bf3505

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

- useCustomNavigate 훅에 replaceLastPath 함수를 추가했습니다.
- 어드민 워크스페이스 메뉴에서 주문 조회를 위한 depth 를 하나 더 추가하였습니다.

2024-10-08 14:33 UTC, Ji-InPark requested changes
확인하고 반영부탁드립니다

2024-10-08 14:33 UTC, Ji-InPark commented on src/types/index.ts
> +}
왜 Order를 사용하지 않고 테이블을 만드셨나요??
일단 서버에서는 해당 타입이 없습니다.

2024-10-08 14:33 UTC, Ji-InPark commented on src/components/admin/order/TableOrderCard.tsx
> +  };
이 부분은 pure하니깐 util 같은 부분으로 추출해서 사용해도 좋을 것 같네요

2024-10-08 14:33 UTC, Ji-InPark commented on src/components/admin/order/TableOrderCard.tsx
> +function TableOrderCard({ id, customerName, createdAt, orderProducts, totalPrice }: Omit<Table, 'status' | 'cancelReason' | 'updatedAt' | 'tableNumber'>) {
굳이 omit을 사용하신 이유가 있나요

2024-10-08 14:33 UTC, Ji-InPark commented on src/components/admin/order/TableOrderCard.tsx
> +  background: #f7f7f7;
자주 사용되는 색이 아닌가요?

2024-10-08 14:33 UTC, Ji-InPark commented on src/components/user/order/OrderTableHistoryCotent.tsx
> +  color: #d8d8d8;
자주 사용되지 않는 색인가요?

2024-10-08 14:33 UTC, Ji-InPark commented on src/components/user/order/OrderTableHistoryCotent.tsx
> +  setSelectedOrderId: Dispatch<SetStateAction<null | number>>;
주문 리스트에서 한 개의 주문을 선택하고 다른 주문을 선택하면 기존에 열렸던 주문 창을 줄이려고 이걸 파라매터로 받는 것 같은데 맞나요??

일단 굳이 한 개만 펼쳐져야 하는지 잘 모르겠습니다. 디자이너랑 상의 후 불필요할 것 같다고 판단되면 이 부분은 수정해주세요

2024-10-08 14:33 UTC, Ji-InPark commented on src/components/user/order/OrderTableHistoryCotent.tsx
> +  const props = { id, customerName, createdAt, orderProducts, totalPrice };
이렇게 다시 할당할거라면 destructure 해서 파라매터 받지 말고
props : OrderTableHistoryProps로 받는게 더 좋을 것 같습니다.

2024-10-08 14:33 UTC, Ji-InPark commented on src/hooks/admin/useAdminWorkspace.tsx
> +  };
이 함수가 왜 workspace hook에 있죠?
해당 함수는 주문 조회 함수입니다. admin order hook으로 옮겨주세요

2024-10-08 14:33 UTC, Ji-InPark commented on src/pages/Admin/AdminWorkspace.tsx
> +          <ImageRouteButton src={orderImage} onClick={() => appendPath('/order-check')} buttonText={'주문 조회'} />
order-check보다 그냥 order만 쓰는게 더 좋아보입니다.

2024-10-08 14:33 UTC, Ji-InPark commented on src/pages/Admin/AdminWorkspace.tsx
> +          <ImageRouteButton src={orderImage} onClick={() => appendPath('/order-check')} buttonText={'주문 조회'} />
그러면 depth가 깊어졌을 때 replaceLastPath를 사용하지 않고
각 페이지 route를 /order/real-time, /order/history, /order/table
이런식으로 표현이 가능하니깐요

2024-10-08 14:33 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderCheck.tsx
> +function AdminOrderCheck() {
여기도 AdminOrder로 바꾸는게 좋을듯 합니다.

그리고 AdminOrders가 헷갈리니 해당 컴포넌트 이름을 AdminOrderRealTime 정도로 바꾸면 좋을 것 같습니다.

2024-10-08 14:33 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderTable.tsx
> +  background: #fff;
자주 사용되지 않는 색상인가요?

2024-10-08 14:33 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderTable.tsx
> +            </TableCell>
cell을 누르면 route가 바뀌나요..?

2024-10-08 14:33 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderTableHistory.tsx
> +  const isEmptyWorkspaces = tables.empty;
tables가 뭔가요...
테이블 별 주문 조회인데 tables가 있는게 모순적이네요... 그리고 해당 데이터 타입은 order가 되는 것이 맞습니다.

우리는 결과적으로 테이블이라는 조건이 달려있는 "주문"을 조회하는 것입니다.

2024-10-08 14:33 UTC, Ji-InPark commented on src/pages/SuperAdmin/SuperAdminUser.tsx
> +import SuperAdminSearchContents from '../../components/SuperAdmin/SuperAdminSearchContents';
왜 superAdmin은 절대 경로 사용하지 않나요?

2024-10-08 14:33 UTC, Ji-InPark commented on src/recoils/atoms.ts
> +    last: false,
필요없는 recoil atom입니다

2024-10-08 18:20 UTC, whddltjdwhd commented on src/types/index.ts
> +}
스웨거를 확인해보니 Order 타입에서 phoneNumber 프로퍼티 삭제, cancelReason 프로퍼티 추가를 한 형태로  응답을 보내주고 있어서 별도의 Table 타입을 생성하였습니다.

2024-10-08 18:23 UTC, whddltjdwhd commented on src/components/admin/order/TableOrderCard.tsx
> +function TableOrderCard({ id, customerName, createdAt, orderProducts, totalPrice }: Omit<Table, 'status' | 'cancelReason' | 'updatedAt' | 'tableNumber'>) {
별도의 interface를 선언하기 보다는 기존 Table 타입에서 명시한 프로퍼티들을 제외하고 사용한다는 의미를 갖추고자 Omit을 사용했습니다. 

즉, 현재 컴포넌트에서는 Table의 프로퍼티들 중 "일부"만 사용중인데, 이를 별도의 interface로 선언하는 것 보다는 Omit을 이용하는게 더 낫다고 생각했습니다.

2024-10-08 18:24 UTC, whddltjdwhd commented on src/components/admin/order/TableOrderCard.tsx
> +  background: #f7f7f7;
3개 이상 사용되네요 enum에 추가하겠습니다.

2024-10-08 18:58 UTC, whddltjdwhd commented on src/pages/Admin/order/AdminOrderTable.tsx
> +            </TableCell>
http://localhost:3000/admin/workspace/8/1?page=0

<Route path="/admin/workspace/:workspaceId/:tableNumber" element={<AdminOrderTableHistory />} />

네 워크스페이스 아이 다음에 테이블 번호가 오도록 바꿉니다.

2024-10-08 19:10 UTC, whddltjdwhd commented on src/components/admin/order/TableOrderCard.tsx
> +function TableOrderCard({ id, customerName, createdAt, orderProducts, totalPrice }: Omit<Table, 'status' | 'cancelReason' | 'updatedAt' | 'tableNumber'>) {
확인해보니까 기존 Order 타입의 프로퍼티가 누락되어 있었네요 Table타입 대신 Order로 모두 바꾸겠습니다

2024-10-08 19:11 UTC, whddltjdwhd commented on src/pages/Admin/order/AdminOrderTableHistory.tsx
> +  const isEmptyWorkspaces = tables.empty;
tablesOrder로 변수명을 바꿨고
확인해보니까 기존 Order 타입의 프로퍼티가 누락되어 있었네요 Table타입 대신 Order로 모두 바꾸겠습니다

2024-10-09 05:01 UTC, Ji-InPark commented on src/components/admin/order/TableOrderCard.tsx
> +function TableOrderCard({ id, customerName, createdAt, orderProducts, totalPrice }: Omit<Table, 'status' | 'cancelReason' | 'updatedAt' | 'tableNumber'>) {
이전에 똑같은 경우가 있을 때는 Omit을 사용하시지 않으셨습니다.
https://github.com/KioSchool/KioSchool/blob/master/src/components/SuperAdmin/workspace/SuperAdminWorkspaceContent.tsx

그리고 omit은 이렇게 파라매터로 받을 때 사용하는 것 보다는 type을 선언할 때 상속과 비슷한 느낌으로 사용하는 경우가 더 많습니다.

2024-10-09 05:10 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrder.tsx
> +      <Container className={'admin-order-check-container'}>
```suggestion
      <Container className={'admin-order-container'}>
```

2024-10-09 05:10 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderTable.tsx
> +      titleNavBarProps={{ title: '테이블 주문 조회', subTitle: '테이블 별 주문 내역을 조회합니다.', onLeftArrowClick: () => replaceLastPath(`/order`) }}
이 부분 제대로 동작하나요?

2024-10-09 05:46 UTC, whddltjdwhd commented on src/pages/Admin/order/AdminOrderTable.tsx
> +      titleNavBarProps={{ title: '테이블 주문 조회', subTitle: '테이블 별 주문 내역을 조회합니다.', onLeftArrowClick: () => replaceLastPath(`/order`) }}
네

2024-10-09 06:22 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderTable.tsx
> +      titleNavBarProps={{ title: '테이블 주문 조회', subTitle: '테이블 별 주문 내역을 조회합니다.', onLeftArrowClick: () => replaceLastPath(`/order`) }}
아 위에서 제 리뷰를 부분만 반영하셨군요.

전 개인적으로 depth가 깊어지면 url상으로도 보여져야 한다고 생각해서 https://github.com/KioSchool/KioSchool/pull/124#discussion_r1791982275 이렇게 리뷰 남겨드렸던거라서요

2024-10-09 07:30 UTC, Ji-InPark approved these changes
수고하셨습니다
반영하고 머지해주세요~

2024-10-09 07:30 UTC, Ji-InPark commented on src/pages/Admin/order/AdminOrderTableHistory.tsx
> +      titleNavBarProps={{ title: `${tableNumber}번 테이블`, onLeftArrowClick: () => replaceLastPath(``) }}
```suggestion
      titleNavBarProps={{ title: `${tableNumber}번 테이블`, onLeftArrowClick: () => replaceLastPath('') }}
```

2024-10-09 07:32 UTC, whddltjdwhd commented on src/pages/SuperAdmin/SuperAdminWorkspace.tsx
> +import SuperAdminSearchContents from '../../components/SuperAdmin/SuperAdminSearchContents';
어라..?

2024-10-09 07:34 UTC, merged