워크스페이스 홈 디자인 적용
KioSchool/KioSchool pull request #58
Opened 2024-03-21 14:55 UTC by whddltjdwhd

## 📚 개요

워크스페이스 홈 디자인을 적용했습니다.

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

![image](https://github.com/KioSchool/KioSchool/assets/81473218/cd9c9ec9-e111-4c83-8a4b-c2eaed654d34)

2024-03-21 14:58 UTC, whddltjdwhd commented
참고로 디자인 구현 못한 부분이 있습니다.
![image](https://github.com/KioSchool/KioSchool/assets/81473218/bdcea59e-f6ab-4256-9bf6-57bf2c4ef4a5)
위 부분은 제 한계로 못했습니다. . .

2024-03-22 06:08 UTC, Ji-InPark requested changes
현재 pr로는 리뷰가 너무 어렵습니다...
컴포넌트로 분리할 수 있는 것은 최대한 분리해주시고 가도성을 챙겨주세요.

ui 처리 부분과 로직이 겹치기 시작하면 앞으로 수정하기 힘든 코드가 됩니다.

한 파일은 최대한 작게 만드는 것을 목표로해주세요. 
한 파일에 코드 150줄 이내로 작성하는 것이 이상적입니다.

2024-03-22 06:08 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
이 파일 너무 심각하게 큽니다...
컴포넌트로 분리할 수 있는건 분리해주세요. 
ex: modal, dummy container 등등

2024-03-22 06:08 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
> +            Array.from({ length: 2 - workspaces.length }, (_, index) => <DummyWorkspaceContainer key={`dummy_${index}`}></DummyWorkspaceContainer>)}
이런식으로 처리하면 이 ui 처리 부분이 어떤걸 의미하는지 이해하기 어렵습니다.

workspaces 변수와 더미 데이터를 합친 새로운 변수(array겠죠?)를 하나 생성하고 이를 사용해서 분리시키는것이 훨씬 가독성이 좋습니다.

AdminOrder.tsx 부분 참고하시면 될 것 같아요.

2024-03-22 10:22 UTC, whddltjdwhd commented on src/pages/Admin/AdminHome.tsx
알겠습니다,,

2024-03-23 12:02 UTC, Ji-InPark requested changes
![image](https://github.com/KioSchool/KioSchool/assets/81283634/cc4bcf83-5775-4880-8f92-6e2cd8d72508)

지금 min-width가 없어서 이렇게 넓이가 작아지면 깨지고 있습니다.
한 1200px 정도로 제한해주시면 좋을 것 같습니다!

그리고 삭제 디자인 구현이 어려우시다면 일단 confirm 창으로 기능만 구현해보세요.

2024-03-23 12:02 UTC, Ji-InPark commented on src/pages/User/Login.tsx
> +  const content = (
Container에서 children을 사용하는 방식으로 수정하면 이 content는 없애고
아래 Container의 children으로 바로 넣어주시면 됩니다.

2024-03-23 12:09 UTC, whddltjdwhd commented on src/components/common/Container/Container.tsx
워크스페이스 컨테이너, 더미 컨테이너, 에드 컨테이너 모두 공통적인 요소가 많아서 prop을 받아 알맞은 컴포넌트를 보여주도록 하려 하고 있습니다.

2024-03-23 12:10 UTC, whddltjdwhd commented on src/components/common/Container/Container.tsx
메인 컨테이너, 서브 컨테이너를 실제로 로그인 창 및 어드민 홈에서 사용하고 있습니다

2024-03-23 12:54 UTC, whddltjdwhd commented on src/components/common/workspace/DummyWorkspace.tsx
> +        Array.from({ length: 2 - props.workspaces.length }, (_, index) => <DummyWorkspaceContainer key={`dummy_${index}`}></DummyWorkspaceContainer>)}
https://devbirdfeet.tistory.com/185
이 글을 참고했는데 위 코드가 좀 더 나은 방법인 것 같다고 생각합니다

2024-03-23 12:58 UTC, Ji-InPark commented on src/components/common/workspace/DummyWorkspace.tsx
> +        Array.from({ length: 2 - props.workspaces.length }, (_, index) => <DummyWorkspaceContainer key={`dummy_${index}`}></DummyWorkspaceContainer>)}
더 나은 방법이라고 생각하시는 이유가 있으신가요??

2024-03-23 13:00 UTC, whddltjdwhd commented on src/components/common/workspace/DummyWorkspace.tsx
> +        Array.from({ length: 2 - props.workspaces.length }, (_, index) => <DummyWorkspaceContainer key={`dummy_${index}`}></DummyWorkspaceContainer>)}
음 더 나은 방법은 아니지만 그렇다고 완전 못 알아볼 정도는 아니라고 생각했습니다

2024-03-23 13:08 UTC, Ji-InPark commented on src/components/common/workspace/DummyWorkspace.tsx
> +        Array.from({ length: 2 - props.workspaces.length }, (_, index) => <DummyWorkspaceContainer key={`dummy_${index}`}></DummyWorkspaceContainer>)}
완전 못알아볼 코드 보다는 잘 읽히는 코드가 더 좋으니깐요!

현재 제가 보면서 힘들었던 점은 먼저 해당 array.from이 작성된 이유부터 해석해야 한다는 점이었습니다.

Array.from을 왜 사용했지?? workspaces가 array 인데? -> 2 - length를 해서 array를 만드는구나. 저건 왜 빼서 만들지? -> 더미 컨테이너를 보여주는 거구나.

이런 흐름이 됩니다. 이런 배경이 되는 이유중 하나는 해당 Array.from으로 만들어진 array는 결국 익명이다 보니 어떤 역할을 하는지 직접 코드를 해석해봐야 한다는 점이 있죠. 또한 로직에 가까운 부분이 UI 선언부에 있어서 더욱더 읽기 힘들게 된 원인이 되지 않았나 싶습니다.

저는 이런 이유로 따로 선언하는게 더 가독성이 좋다고 판단한 것인데요
위 코드가 제가 말한 이점보다 얻는 이점이 더 크지 않는 이상 반영해주시면 좋을 것 같습니다!

2024-03-23 13:19 UTC, whddltjdwhd commented on src/components/common/workspace/DummyWorkspace.tsx
> +        Array.from({ length: 2 - props.workspaces.length }, (_, index) => <DummyWorkspaceContainer key={`dummy_${index}`}></DummyWorkspaceContainer>)}
아하 알겠습니다!

2024-03-23 13:44 UTC, whddltjdwhd commented on src/pages/Admin/AdminHome.tsx
> +      {modalOpen && <InputModal onClick={setModalClose} onSubmit={createHandler} content={modalContent} />}
모달 책임을 옮기라는 의미가 useState를 AddWorkspace 내부로 옮기라는 말씀이실까요?

2024-03-23 13:45 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
> +      {modalOpen && <InputModal onClick={setModalClose} onSubmit={createHandler} content={modalContent} />}
state도 그렇고 실질적으로 modal 띄우는 것도 그렇구요

2024-03-23 13:53 UTC, whddltjdwhd commented on src/pages/Admin/AdminHome.tsx
> +      {modalOpen && <InputModal onClick={setModalClose} onSubmit={createHandler} content={modalContent} />}
알겠습니다

2024-03-23 14:58 UTC, Ji-InPark reviewed
키오스쿨에서는 기본적으로 function을 사용하여 컴포넌트를 정의하고 있습니다.
웬만하면 function으로 통일해주세요!

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/Container/Container.tsx
> +};
```suggestion
interface ContainerProps = {
  children: JSX.Element;
  justifyValue: string;
};
```

해당 파일 이름과 똑같이 유지하는 편이 좋다고 생각합니다. 상속받아서 사용하는 경우가 아니라면 그냥 Props만 적어도 괜찮다고 생각하기도 하구요

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/content/AddworkspaceModalContent.tsx
> +};
WrapperProps로 이름 지은 이유가 있나요?? 그리고 type보다는 interface를 사용하는 편이 좋습니다.
이유는 저도 기억이 안나서 찾아보시면 될 것 같아요

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/content/WorkspaceContent.tsx
> +const WorkspaceContent = ({ workspaces, leaveHandler }: WrapperProps) => {
leaveHandler를 밖에서 주입받아야하는 이유가 있나요??

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/workspace/AddWorkspace.tsx
> +  const maxWorkspaceNum = 3;
```suggestion
  const maxWorkspaceNumber = 3;
```

줄인다면 num으로 줄이는 것보다는 no로 더 많이 줄이는 편이긴 합니다

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/modal/InputModal.tsx
> +      <ModalContent onSubmit={createHandler}>{children}</ModalContent>
InputModal인데 createHandler를 파라매터로 받아서 처리하는게 조금 어색하네요

컴포넌트 이름이 잘못되었거나 파라매터명이 잘못되어서 생기는 어색함 같습니다.

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/workspace/AddWorkspace.tsx
> +    setModalOpen(false);
```suggestion
    closeModal();
```

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/workspace/DummyWorkspace.tsx
> +      {maxDummyWorkspaceNum > workspaces.length &&
이 부분도 early return 해주면 좋을 것 같네요

2024-03-23 14:58 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
> +    if (userInput) leaveWorkspaces(id);
```suggestion
    if (userInput) leaveWorkspace(id);
```

이걸 이제 봤네...

2024-03-23 14:58 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
> +    if (userInput) leaveWorkspaces(id);
hook에서 바꿔주세여~

2024-03-23 14:58 UTC, Ji-InPark commented on src/components/common/Container/Container.tsx
폴더명 소문자로 안바꾸셨네여
저는 실행할 때 에러나던데 에러 안나요?

2024-03-23 15:00 UTC, whddltjdwhd commented on src/components/common/Container/Container.tsx
엥 저는 바뀐걸로 나와요
![image](https://github.com/KioSchool/KioSchool/assets/81473218/3db2a195-e184-4e05-b4d2-f148a4340348)

2024-03-23 15:01 UTC, Ji-InPark commented on src/components/common/Container/Container.tsx
깃헙에는 안올라왔는데... 다시 한 번 확인해봐쥇여

2024-03-23 15:17 UTC, whddltjdwhd commented on src/components/common/Container/Container.tsx
다시 확인해봤는데도 제 환경에선 소문자에요ㅠ

2024-03-23 15:19 UTC, Ji-InPark commented on src/components/common/Container/Container.tsx
finder나 explorer로 확인해봐도 그런가요?

2024-03-23 15:20 UTC, whddltjdwhd commented on src/components/common/Container/Container.tsx
![image](https://github.com/KioSchool/KioSchool/assets/81473218/78615f6c-c942-4bd2-b4ec-b38311a05298)

네

2024-03-23 15:22 UTC, Ji-InPark commented on src/components/common/Container/Container.tsx
그럼 폴더명 바꾸고 다시 바꿔보시죵

2024-03-23 15:44 UTC, Ji-InPark reviewed
처음보다 훨씬 깔끔해졌네요
다만 이전 리뷰인 function으로 처리하는 것은 아직 반영이 안된 것 같습니다! 

이 부분 확인 부탁드릴게요

2024-03-23 15:44 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
>      </>
필요없는 fragment 들 지워주세요

2024-03-23 15:44 UTC, Ji-InPark commented on src/components/common/modal/CreateWorkspaceModal.tsx
이제 이 파일은 common의 modal이 아닌 workspace에 modal 폴더를 더 만들어서 이동하는게 좋겠네요

2024-03-23 15:44 UTC, Ji-InPark commented on src/components/common/modal/CreateWorkspaceModal.tsx
또는 modal 폴더에 workspace 폴더를 만들던가요

2024-03-23 15:44 UTC, Ji-InPark commented on src/components/common/content/WorkspaceContent.tsx
> +              <DeleteContainer>
나중에는 DeleteContainer에도 hover css가 필요할 것 같긴합니다.

2024-03-23 15:44 UTC, Ji-InPark commented on src/components/common/content/WorkspaceContent.tsx
> +`;
![image](https://github.com/KioSchool/KioSchool/assets/81283634/12f64e5f-a17a-4a8d-aa63-16865073c3e8)

글자가 충분히 안잘릴 수 있을 것 같은데 잘리고 있습니다
이 부분 한 번 확인해주세요

2024-03-23 16:04 UTC, whddltjdwhd commented on src/components/common/content/WorkspaceContent.tsx
> +`;
![image](https://github.com/KioSchool/KioSchool/assets/81473218/53b5f30f-8b7f-49cb-9df4-beb9f3dd5048)
네 해결했습니다

2024-03-23 16:05 UTC, Ji-InPark approved these changes
```
 __           __           
|  |    _____/  |_  _____  
|  |   / ___\   __\/     \ 
|  |__/ /_/  |  | |  | |  \
|____/\___  /|__| |__|_|  /
     /_____/            \/ 
```

수고하셨습니다!

2024-03-23 16:05 UTC, Ji-InPark commented on src/pages/Admin/AdminHome.tsx
> +      <>
얘도 필요 없지 않아요?

2024-03-23 16:06 UTC, whddltjdwhd commented on src/pages/Admin/AdminHome.tsx
> +      <>
얘는 childern prop으로 받는 애여서 프래그먼트로 감싸줘야 하더라구요

2024-03-23 16:10 UTC, merged