카테고리 Drag and Drop 디자인 적용
KioSchool/KioSchool pull request #78
Opened 2024-05-03 02:18 UTC by whddltjdwhd

## 📚 개요

카테고리 Drag and Drop 디자인 적용입니다.

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

2024-05-03 10:42 UTC, Ji-InPark requested changes

2024-05-03 10:42 UTC, Ji-InPark commented on src/components/common/content/DragAndDropContent.tsx
> +    };
이게 어떤 역할을 하는 코드인가요?

2024-05-03 10:42 UTC, Ji-InPark commented on src/components/common/input/AppInput.tsx
> +  }
focus 할 때 outline이 전체적으로 다 없어지는게 맞다고 생각하신건가요??

2024-05-03 10:42 UTC, Ji-InPark commented on src/components/common/input/AppInputWithButton.tsx
> +const CategoriesInputSubContainer = styled.div`
```suggestion
const CategoriesInputContainer = styled.div`
```

왜 sub container라고 지으셨나요??

2024-05-03 10:42 UTC, Ji-InPark commented on src/components/common/input/AppInputWithButton.tsx
> +  onclick: () => void;
```suggestion
  onClick: () => void;
```

2024-05-03 10:42 UTC, Ji-InPark commented on src/components/common/nav/TitleNavBar.tsx
> +    <Container useSubTitle={subTitle !== ''}>
```suggestion
    <Container useSubTitle={subTitle}>
```

이렇게 안되나요?? 안되면 !!subTitle도 있고 subTitle.isEmpty() 같은 것도 있을 것 같아요

2024-05-03 10:42 UTC, Ji-InPark commented on src/hooks/admin/useAdminProducts.tsx
> +  const reorderCategories = (categoryIds: number[]) => {
```suggestion
  const reorderCategories = (productCategoryIds: number[]) => {
```
로 바꿔서 아래 workspaceId처럼 줄여서 넣을 수 있게 하시죠~

2024-05-03 10:42 UTC, Ji-InPark commented on src/hooks/admin/useAdminProducts.tsx
>    const addCategories = (name: string) => {
```suggestion
  const addCategory = (name: string) => {
```
옛날에 이름 잘못 지었었네요

2024-05-03 10:42 UTC, Ji-InPark commented on src/pages/Admin/AdminProductCategoires.tsx
> +  padding-bottom: 100px;
이거 padding: 0 100px; 였나
쨋든 한 줄로 쓸 수 있어요

2024-05-03 10:42 UTC, Ji-InPark commented on src/pages/Admin/AdminProductCategoires.tsx
> +  height: 300px;
```suggestion
  height: 500px;
```

지금은 좀 좁아서 카테고리가 가려지는 갯수가 많은 것 같아요
좀 더 높여서 많은 카테고리가 보이게끔 하시죠

2024-05-03 10:42 UTC, Ji-InPark commented on src/pages/Admin/AdminProductCategoires.tsx
> +      <AppContainer justifyValue={'center'}>
```suggestion
      <AppContainer justifyValue={'center'}>
```
AppContainer 내부에 navbar있습니다

2024-05-03 10:42 UTC, Ji-InPark commented on src/pages/Admin/AdminProductCategoires.tsx
> +  };
```suggestion
  const saveCategoriesOrder = () => {
    const categoriesId = rawCategories.map((itm) => itm.id);
    reorderCategories(categoriesId);
  };
```

fix도 맞긴한데 고치다로도 해석될 수 있으니 이런 네이밍이 더 좋은 것 같습니다

2024-05-03 13:38 UTC, whddltjdwhd commented on src/components/common/content/DragAndDropContent.tsx
> +    };
긁어오느라 넣었는데 없어도 잘 돌아가네요ㅎㅎ..삭제했습니다

2024-05-03 13:47 UTC, whddltjdwhd commented on src/components/common/input/AppInput.tsx
> +  }
그렇게 생각했었는데 있어도 이쁘네요 넣겠습니다

2024-05-03 16:43 UTC, Ji-InPark commented on src/components/common/input/AppInputWithButton.tsx
> +  onclick: () => void;
어허 반영안하시고 resolve하시면 안됩니다

2024-05-03 16:43 UTC, Ji-InPark commented on src/pages/Admin/AdminProductCategoires.tsx
> +    <>
필요없는 fragment입니다

2024-05-03 16:43 UTC, Ji-InPark commented on src/pages/Admin/AdminProductCategoires.tsx
> +              }}
```suggestion
              onClick={saveCategory}
```

2024-05-04 12:21 UTC, Ji-InPark approved these changes
![image](https://github.com/KioSchool/KioSchool/assets/81283634/6b57c7fc-c22f-4386-89d9-c05300b45d9a)

2024-05-04 12:21 UTC, Ji-InPark commented
rebase하고 머지해주세요~

2024-05-04 12:26 UTC, merged